/* Generated By:JavaCC: Do not edit this line. FunConstants.java */
package parser;

public interface FunConstants {

  int EOF = 0;
  int BREAK = 12;
  int CLASS = 13;
  int CONSTRUCTOR = 14;
  int ELSE = 15;
  int EXTENDS = 16;
  int FOR = 17;
  int IF = 18;
  int NEW = 19;
  int PRINT = 20;
  int READ = 21;
  int RETURN = 22;
  int SUPER = 23;
  int PRIMITIVE_TYPE = 24;
  int INT = 25;
  int STRING = 26;
  int CHAR = 27;
  int FLOAT = 28;
  int BOOLEAN = 29;
  int ASSIGN = 30;
  int GT = 31;
  int LT = 32;
  int EQ = 33;
  int LE = 34;
  int GE = 35;
  int NEQ = 36;
  int PLUS = 37;
  int MINUS = 38;
  int MULTIPLY = 39;
  int DIVIDE = 40;
  int REM = 41;
  int NOT = 42;
  int XOR = 43;
  int AND = 44;
  int OR = 45;
  int LPAREN = 46;
  int RPAREN = 47;
  int LBRACE = 48;
  int RBRACE = 49;
  int LBRACKET = 50;
  int RBRACKET = 51;
  int SEMICOLON = 52;
  int COMMA = 53;
  int SINGLEQUOTATIONMARKS = 54;
  int DOT = 55;
  int COLON = 56;
  int number_constant = 57;
  int int_literal = 58;
  int float_literal = 59;
  int string_constant = 60;
  int null_constant = 61;
  int CHARACTER = 62;
  int EXPONENT = 63;
  int boolean_constant = 64;
  int IDENT = 65;
  int LETTER = 66;
  int DIGIT = 67;
  int UNDERSCORE = 68;
  int INVALID_LEXICAL = 69;
  int INVALID_CONST = 70;

  int DEFAULT = 0;
  int multilinecomment = 1;
  int singlelinecomment = 2;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"/*\"",
    "\"//\"",
    "\"*/\"",
    "<token of kind 9>",
    "<token of kind 10>",
    "<token of kind 11>",
    "\"break\"",
    "\"class\"",
    "\"constructor\"",
    "\"else\"",
    "\"extends\"",
    "\"for\"",
    "\"if\"",
    "\"new\"",
    "\"print\"",
    "\"read\"",
    "\"return\"",
    "\"super\"",
    "<PRIMITIVE_TYPE>",
    "\"int\"",
    "\"string\"",
    "\"char\"",
    "\"float\"",
    "\"boolean\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"NOT\"",
    "\"XOR\"",
    "\"AND\"",
    "\"OR\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\"\\\'\"",
    "\".\"",
    "\":\"",
    "<number_constant>",
    "<int_literal>",
    "<float_literal>",
    "<string_constant>",
    "\"null\"",
    "<CHARACTER>",
    "<EXPONENT>",
    "<boolean_constant>",
    "<IDENT>",
    "<LETTER>",
    "<DIGIT>",
    "\"_\"",
    "<INVALID_LEXICAL>",
    "<INVALID_CONST>",
  };

}
