/* Generated By:JavaCC: Do not edit this line. FunConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FunConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BREAK = 12;
  /** RegularExpression Id. */
  int CLASS = 13;
  /** RegularExpression Id. */
  int CONSTRUCTOR = 14;
  /** RegularExpression Id. */
  int ELSE = 15;
  /** RegularExpression Id. */
  int EXTENDS = 16;
  /** RegularExpression Id. */
  int FOR = 17;
  /** RegularExpression Id. */
  int IF = 18;
  /** RegularExpression Id. */
  int NEW = 19;
  /** RegularExpression Id. */
  int PRINT = 20;
  /** RegularExpression Id. */
  int READ = 21;
  /** RegularExpression Id. */
  int RETURN = 22;
  /** RegularExpression Id. */
  int SUPER = 23;
  /** RegularExpression Id. */
  int PRIMITIVE_TYPE = 24;
  /** RegularExpression Id. */
  int INT = 25;
  /** RegularExpression Id. */
  int STRING = 26;
  /** RegularExpression Id. */
  int CHAR = 27;
  /** RegularExpression Id. */
  int FLOAT = 28;
  /** RegularExpression Id. */
  int BOOLEAN = 29;
  /** RegularExpression Id. */
  int ASSIGN = 30;
  /** RegularExpression Id. */
  int GT = 31;
  /** RegularExpression Id. */
  int LT = 32;
  /** RegularExpression Id. */
  int EQ = 33;
  /** RegularExpression Id. */
  int LE = 34;
  /** RegularExpression Id. */
  int GE = 35;
  /** RegularExpression Id. */
  int NEQ = 36;
  /** RegularExpression Id. */
  int PLUS = 37;
  /** RegularExpression Id. */
  int MINUS = 38;
  /** RegularExpression Id. */
  int MULTIPLY = 39;
  /** RegularExpression Id. */
  int DIVIDE = 40;
  /** RegularExpression Id. */
  int REM = 41;
  /** RegularExpression Id. */
  int NOT = 42;
  /** RegularExpression Id. */
  int XOR = 43;
  /** RegularExpression Id. */
  int AND = 44;
  /** RegularExpression Id. */
  int OR = 45;
  /** RegularExpression Id. */
  int LPAREN = 46;
  /** RegularExpression Id. */
  int RPAREN = 47;
  /** RegularExpression Id. */
  int LBRACE = 48;
  /** RegularExpression Id. */
  int RBRACE = 49;
  /** RegularExpression Id. */
  int LBRACKET = 50;
  /** RegularExpression Id. */
  int RBRACKET = 51;
  /** RegularExpression Id. */
  int SEMICOLON = 52;
  /** RegularExpression Id. */
  int COMMA = 53;
  /** RegularExpression Id. */
  int SINGLEQUOTATIONMARKS = 54;
  /** RegularExpression Id. */
  int DOT = 55;
  /** RegularExpression Id. */
  int COLON = 56;
  /** RegularExpression Id. */
  int int_literal = 57;
  /** RegularExpression Id. */
  int float_literal = 58;
  /** RegularExpression Id. */
  int string_constant = 59;
  /** RegularExpression Id. */
  int null_constant = 60;
  /** RegularExpression Id. */
  int char_const = 61;
  /** RegularExpression Id. */
  int EXPONENT = 62;
  /** RegularExpression Id. */
  int boolean_constant = 63;
  /** RegularExpression Id. */
  int IDENT = 64;
  /** RegularExpression Id. */
  int LETTER = 65;
  /** RegularExpression Id. */
  int DIGIT = 66;
  /** RegularExpression Id. */
  int UNDERSCORE = 67;
  /** RegularExpression Id. */
  int INVALID_LEXICAL = 68;
  /** RegularExpression Id. */
  int INVALID_CONST = 69;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int multilinecomment = 1;
  /** Lexical state. */
  int singlelinecomment = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"/*\"",
    "\"//\"",
    "\"*/\"",
    "<token of kind 9>",
    "<token of kind 10>",
    "<token of kind 11>",
    "\"break\"",
    "\"class\"",
    "\"constructor\"",
    "\"else\"",
    "\"extends\"",
    "\"for\"",
    "\"if\"",
    "\"new\"",
    "\"print\"",
    "\"read\"",
    "\"return\"",
    "\"super\"",
    "<PRIMITIVE_TYPE>",
    "\"int\"",
    "\"string\"",
    "\"char\"",
    "\"float\"",
    "\"boolean\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"NOT\"",
    "\"XOR\"",
    "\"AND\"",
    "\"OR\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\"\\\'\"",
    "\".\"",
    "\":\"",
    "<int_literal>",
    "<float_literal>",
    "<string_constant>",
    "\"null\"",
    "<char_const>",
    "<EXPONENT>",
    "<boolean_constant>",
    "<IDENT>",
    "<LETTER>",
    "<DIGIT>",
    "\"_\"",
    "<INVALID_LEXICAL>",
    "<INVALID_CONST>",
  };

}
