/* Generated By:JavaCC: Do not edit this line. FunConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FunConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BREAK = 12;
  /** RegularExpression Id. */
  int CLASS = 13;
  /** RegularExpression Id. */
  int CONSTRUCTOR = 14;
  /** RegularExpression Id. */
  int ELSE = 15;
  /** RegularExpression Id. */
  int EXTENDS = 16;
  /** RegularExpression Id. */
  int FOR = 17;
  /** RegularExpression Id. */
  int IF = 18;
  /** RegularExpression Id. */
  int NEW = 19;
  /** RegularExpression Id. */
  int PRINT = 20;
  /** RegularExpression Id. */
  int READ = 21;
  /** RegularExpression Id. */
  int RETURN = 22;
  /** RegularExpression Id. */
  int SUPER = 23;
  /** RegularExpression Id. */
  int PRIMITIVE_TYPE = 24;
  /** RegularExpression Id. */
  int INT = 25;
  /** RegularExpression Id. */
  int STRING = 26;
  /** RegularExpression Id. */
  int CHAR = 27;
  /** RegularExpression Id. */
  int DOUBLE = 28;
  /** RegularExpression Id. */
  int BYTE = 29;
  /** RegularExpression Id. */
  int SHORT = 30;
  /** RegularExpression Id. */
  int LONG = 31;
  /** RegularExpression Id. */
  int FLOAT = 32;
  /** RegularExpression Id. */
  int CONSTANT = 33;
  /** RegularExpression Id. */
  int DIGIT = 34;
  /** RegularExpression Id. */
  int ASSIGN = 35;
  /** RegularExpression Id. */
  int GT = 36;
  /** RegularExpression Id. */
  int LT = 37;
  /** RegularExpression Id. */
  int EQ = 38;
  /** RegularExpression Id. */
  int LE = 39;
  /** RegularExpression Id. */
  int GE = 40;
  /** RegularExpression Id. */
  int NEQ = 41;
  /** RegularExpression Id. */
  int PLUS = 42;
  /** RegularExpression Id. */
  int MINUS = 43;
  /** RegularExpression Id. */
  int MULTIPLY = 44;
  /** RegularExpression Id. */
  int DIVIDE = 45;
  /** RegularExpression Id. */
  int REM = 46;
  /** RegularExpression Id. */
  int BOOLEAN = 47;
  /** RegularExpression Id. */
  int NOT = 48;
  /** RegularExpression Id. */
  int XOR = 49;
  /** RegularExpression Id. */
  int AND = 50;
  /** RegularExpression Id. */
  int OR = 51;
  /** RegularExpression Id. */
  int LPAREN = 52;
  /** RegularExpression Id. */
  int RPAREN = 53;
  /** RegularExpression Id. */
  int LBRACE = 54;
  /** RegularExpression Id. */
  int RBRACE = 55;
  /** RegularExpression Id. */
  int LBRACKET = 56;
  /** RegularExpression Id. */
  int RBRACKET = 57;
  /** RegularExpression Id. */
  int SEMICOLON = 58;
  /** RegularExpression Id. */
  int COMMA = 59;
  /** RegularExpression Id. */
  int SINGLEQUOTATIONMARKS = 60;
  /** RegularExpression Id. */
  int DOT = 61;
  /** RegularExpression Id. */
  int COLON = 62;
  /** RegularExpression Id. */
  int int_constant = 63;
  /** RegularExpression Id. */
  int string_constant = 64;
  /** RegularExpression Id. */
  int null_constant = 65;
  /** RegularExpression Id. */
  int int_literal = 66;
  /** RegularExpression Id. */
  int float_literal = 67;
  /** RegularExpression Id. */
  int CHARACTER = 68;
  /** RegularExpression Id. */
  int EXPONENT = 69;
  /** RegularExpression Id. */
  int IDENT = 70;
  /** RegularExpression Id. */
  int LETTER = 71;
  /** RegularExpression Id. */
  int INVALID_LEXICAL = 72;
  /** RegularExpression Id. */
  int INVALID_CONST = 73;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int multilinecomment = 1;
  /** Lexical state. */
  int singlelinecomment = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"/*\"",
    "\"//\"",
    "\"*/\"",
    "<token of kind 9>",
    "<token of kind 10>",
    "<token of kind 11>",
    "\"break\"",
    "\"class\"",
    "\"constructor\"",
    "\"else\"",
    "\"extends\"",
    "\"for\"",
    "\"if\"",
    "\"new\"",
    "\"print\"",
    "\"read\"",
    "\"return\"",
    "\"super\"",
    "<PRIMITIVE_TYPE>",
    "\"int\"",
    "\"string\"",
    "\"char\"",
    "\"double\"",
    "\"byte\"",
    "\"short\"",
    "\"long\"",
    "\"float\"",
    "<CONSTANT>",
    "<DIGIT>",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "<BOOLEAN>",
    "\"not\"",
    "\"xor\"",
    "\"and\"",
    "\"or\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\"\\\'\"",
    "\".\"",
    "\":\"",
    "<int_constant>",
    "<string_constant>",
    "\"null\"",
    "<int_literal>",
    "<float_literal>",
    "<CHARACTER>",
    "<EXPONENT>",
    "<IDENT>",
    "<LETTER>",
    "<INVALID_LEXICAL>",
    "<INVALID_CONST>",
  };

}
