/* Generated By:JavaCC: Do not edit this line. FunConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FunConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BREAK = 11;
  /** RegularExpression Id. */
  int CLASS = 12;
  /** RegularExpression Id. */
  int CONSTRUCTOR = 13;
  /** RegularExpression Id. */
  int ELSE = 14;
  /** RegularExpression Id. */
  int EXTENDS = 15;
  /** RegularExpression Id. */
  int FOR = 16;
  /** RegularExpression Id. */
  int IF = 17;
  /** RegularExpression Id. */
  int NEW = 18;
  /** RegularExpression Id. */
  int PRINT = 19;
  /** RegularExpression Id. */
  int READ = 20;
  /** RegularExpression Id. */
  int RETURN = 21;
  /** RegularExpression Id. */
  int SUPER = 22;
  /** RegularExpression Id. */
  int INT = 23;
  /** RegularExpression Id. */
  int STRING = 24;
  /** RegularExpression Id. */
  int CHAR = 25;
  /** RegularExpression Id. */
  int DOUBLE = 26;
  /** RegularExpression Id. */
  int FLOAT = 27;
  /** RegularExpression Id. */
  int ASSIGN = 28;
  /** RegularExpression Id. */
  int GT = 29;
  /** RegularExpression Id. */
  int LT = 30;
  /** RegularExpression Id. */
  int EQ = 31;
  /** RegularExpression Id. */
  int LE = 32;
  /** RegularExpression Id. */
  int GE = 33;
  /** RegularExpression Id. */
  int NEQ = 34;
  /** RegularExpression Id. */
  int PLUS = 35;
  /** RegularExpression Id. */
  int MINUS = 36;
  /** RegularExpression Id. */
  int MULTIPLY = 37;
  /** RegularExpression Id. */
  int DIVIDE = 38;
  /** RegularExpression Id. */
  int REM = 39;
  /** RegularExpression Id. */
  int BOOLEAN = 40;
  /** RegularExpression Id. */
  int XOR = 41;
  /** RegularExpression Id. */
  int NOT = 42;
  /** RegularExpression Id. */
  int AND = 43;
  /** RegularExpression Id. */
  int OR = 44;
  /** RegularExpression Id. */
  int LPAREN = 45;
  /** RegularExpression Id. */
  int RPAREN = 46;
  /** RegularExpression Id. */
  int LBRACE = 47;
  /** RegularExpression Id. */
  int RBRACE = 48;
  /** RegularExpression Id. */
  int LBRACKET = 49;
  /** RegularExpression Id. */
  int RBRACKET = 50;
  /** RegularExpression Id. */
  int SEMICOLON = 51;
  /** RegularExpression Id. */
  int COMMA = 52;
  /** RegularExpression Id. */
  int DOT = 53;
  /** RegularExpression Id. */
  int SINGLE_QUOTATION_MARKS = 54;
  /** RegularExpression Id. */
  int int_constant = 55;
  /** RegularExpression Id. */
  int string_constant = 56;
  /** RegularExpression Id. */
  int null_constant = 57;
  /** RegularExpression Id. */
  int int_literal = 58;
  /** RegularExpression Id. */
  int float_literal = 59;
  /** RegularExpression Id. */
  int CHARACTER = 60;
  /** RegularExpression Id. */
  int EXPONENT = 61;
  /** RegularExpression Id. */
  int CONSTANT = 62;
  /** RegularExpression Id. */
  int IDENT = 63;
  /** RegularExpression Id. */
  int LETTER = 64;
  /** RegularExpression Id. */
  int DIGIT = 65;
  /** RegularExpression Id. */
  int primitivetype = 66;
  /** RegularExpression Id. */
  int INVALID_LEXICAL = 67;
  /** RegularExpression Id. */
  int INVALID_CONSTANT = 68;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int singlelinecomment = 1;
  /** Lexical state. */
  int multilinecomment = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"/*\"",
    "\"//\"",
    "<token of kind 3>",
    "<token of kind 4>",
    "\"*/\"",
    "<token of kind 6>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"break\"",
    "\"class\"",
    "\"constructor\"",
    "\"else\"",
    "\"extends\"",
    "\"for\"",
    "\"if\"",
    "\"new\"",
    "\"print\"",
    "\"read\"",
    "\"return\"",
    "\"super\"",
    "\"int\"",
    "\"string\"",
    "\"char\"",
    "\"double\"",
    "\"float\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "<BOOLEAN>",
    "\"xor\"",
    "\"not\"",
    "\"and\"",
    "\"or\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"\\\'\"",
    "<int_constant>",
    "<string_constant>",
    "\"null\"",
    "<int_literal>",
    "<float_literal>",
    "<CHARACTER>",
    "<EXPONENT>",
    "<CONSTANT>",
    "<IDENT>",
    "<LETTER>",
    "<DIGIT>",
    "<primitivetype>",
    "<INVALID_LEXICAL>",
    "<INVALID_CONSTANT>",
  };

}
